import { Arizonia, Geist, Geist_Mono, Great_Vibes, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const opensans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const arizonia = Arizonia({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arizonia",
  weight: ["400"],
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: ['400'],
  display: 'swap'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Concerned Country Care",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${opensans.variable} ${arizonia.variable} ${greatVibes.variable}`}>
        {children}
      </body>
    </html>
  );
}
